### PR TITLE
Feature/weekly tasks

### PR DESCRIPTION
**Pull request by issac211**
Added tables, routers, tests, templates, and internal functions

The fitter gives the option to set weekly tasks.
Comes with a page for managing weekly tasks and another page for editing the task.
Gives the ability to edit, add and delete a weekly task.

Along with this in the feature is included a function for creating the tasks - which aims to create tasks every week for the user (according to the definition of his weekly tasks)

### CODE REVIEW

**Comment by issac211** [comment]
There seems to be a problem with the checks.
If it's critical, any suggestions on how to resolve it?

**Comment by PureDreamer** [comment]
image

this is the error you are getting.. on your computer do the tests work?

**Comment by issac211** [comment]
> image
> 
> this is the error you are getting.. on your computer do the tests work?

Yes, I checked on my computer after the Merge. it seems like it didn't run the tests.. maybe another pull request will do the trick?
I just don't know if it's necessary

**Comment by PureDreamer** [comment]
> 
> 
> > image
> > this is the error you are getting.. on your computer do the tests work?
> 
> Yes, I checked on my computer after the Merge and it passed the tests.
> it seems like it didn't run the tests.. maybe another pull request will do the trick?
> I just don't know if it's necessary

You have to pass all the tests for it to be merged, so you need to find what's the problem.

**Pull request closed without merging**
